version: '3.5'

services:

  mc-php-cli:
    container_name: mc-php-cli
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
    - .:/var/www
    - composer:/root/.composer/cache

volumes:
  composer: